version: '3'

services:
  java:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8011:8080"
    restart: on-failure
    container_name: java_application
    depends_on:
      - db
  db:
    image: mariadb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/main/resources/db/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: lechery-spangle-tucson-marina-psaltery
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic

